<?xml version="1.0"?>
<!--
Software License Agreement (BSD)

\file      khan.urdf.xacro
\authors   Coleman Knabe <csknabe@gmail.com> based on work by Paul Bovbel <pbovbel@clearpathrobotics.com>, Devon Ash <dash@clearpathrobotics.com>
\copyright Copyright (c) 2015, Clearpath Robotics, Inc., All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that
the following conditions are met:
 * Redistributions of source code must retain the above copyright notice, this list of conditions and the
   following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
   following disclaimer in the documentation and/or other materials provided with the distribution.
 * Neither the name of Clearpath Robotics nor the names of its contributors may be used to endorse or promote
   products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WAR-
RANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, IN-
DIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<robot name="khan_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Included URDF/XACRO Files -->
  <xacro:include filename="$(find khan_description)/urdf/decorations.urdf.xacro" />
  <xacro:include filename="$(find khan_description)/urdf/wheel.urdf.xacro" />

  <property name="M_PI" value="3.14159"/>

  <!-- Base Size -->
  <property name="base_x_size" value="0.245" />
  <property name="base_y_size" value="0.153" />
  <property name="base_z_size" value="0.074" />
  <property name="base_z_clearance" value="0.021" />

  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="0.185" />
  <xacro:property name="track" value="0.189" />
  <xacro:property name="wheel_vertical_offset" value="0.0" />

  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.036" />
  <xacro:property name="wheel_radius" value="0.03" />

  <xacro:macro name="khan_robot">

    <!-- Base link is the center of the robot's base on ground -->
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://khan_description/meshes/rover_base_with_tread.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision> <!--FIXME-->
        <origin xyz="0 0 ${base_z_clearance/2+base_z_size/2}" rpy="0 0 0" />
        <geometry>
          <box size="${base_x_size} ${base_y_size} ${base_z_size-base_z_clearance}"/>
        </geometry>
      </collision>
    </link>

    <!-- Base footprint is on the ground under the robot -->
    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="base_footprint" />
    </joint>

    <!-- Interial link stores the robot's inertial information -->
    <link name="inertial_link"> <!--FIXME currently made up -->
      <inertial>
        <mass value="0.8" />
        <origin xyz="0.0 0.0 0.035" />
        <inertia ixx="0.1" ixy="-0.001" ixz="-0.001" iyy="0.3" iyz="-0.0001" izz="0.3" />
      </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="inertial_link" />
    </joint>
    
    <link name="hokuyo_link">
      <inertial>
        <mass value ="0.1" />
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
      </inertial>
      <visual name="visual">
        <geometry>
          <mesh filename="model://hokuyo/meshes/hokuyo.dae" scale="1 1 1"/>
        </geometry>
      </visual>
      <sensor name="laser" type="ray">
        <pose>0.01 0 0.03 0 -0 0</pose>
        <ray>
          <scan>
            <horizontal>
              <samples>640</samples>
              <resolution>1</resolution>
              <min_angle>-2.26889</min_angle>
              <max_angle>2.268899</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.08</min>
            <max>10</max>
            <resolution>0.01</resolution>
          </range>
        </ray>

        <plugin name="laser" filename="libRayPlugin.so" />
        <always_on>1</always_on>
        <update_rate>30</update_rate>
        <visualize>true</visualize>
      </sensor>
    </link>

    <joint name="hokuyo_joint" type="fixed">
      <origin xyz="0.06 0 0.109" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="hokuyo_link" />
    </joint>

    <gazebo reference="hokuyo_link">
    <sensor type="gpu_ray" name="head_hokuyo_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.570796</min_angle>
            <max_angle>1.570796</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <!-- Noise parameters based on published spec for Hokuyo laser
               achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
               stddev of 0.01m will put 99.7% of samples within 0.03m of the true
               reading. -->
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_gpu_laser.so">
        <topicName>/khan/laser/scan</topicName>
        <frameName>hokuyo_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

    <!-- Khan wheel macros -->
    <xacro:khan_wheel wheel_prefix="front_left">
      <origin xyz="${wheelbase/2} ${track/2} ${wheel_radius}" rpy="0 0 0" />
    </xacro:khan_wheel>
    <xacro:khan_wheel wheel_prefix="front_right">
      <origin xyz="${wheelbase/2} ${-track/2} ${wheel_radius}" rpy="0 0 0" />
    </xacro:khan_wheel>
    <xacro:khan_wheel wheel_prefix="rear_left">
      <origin xyz="${-wheelbase/2} ${track/2} ${wheel_radius}" rpy="0 0 0" />
    </xacro:khan_wheel>
    <xacro:khan_wheel wheel_prefix="rear_right">
      <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_radius}" rpy="0 0 0" />
    </xacro:khan_wheel>

<!--    <xacro:khan_decorate /> FIXME if we want to put tracks as a decoration rather than part of base-->
  </xacro:macro>
</robot>
